rom_config: '../../../extract/usa/config.yaml'
build_path: '../../../build/usa'
delinks_path: '../../../build/usa/delinks'
main_module:
  name: main
  object: '../../../build/usa/build/arm9.bin'
  hash: cd9962f029d97e4d
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../../build/usa/build/itcm.bin'
  hash: '2599c7b40e54c58f'
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../../build/usa/build/dtcm.bin'
  hash: ea8d2d4ad6369eee
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: '../../../build/usa/build/arm9_ov000.bin'
  hash: '04549d61f225fbd4'
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: '../../../build/usa/build/arm9_ov001.bin'
  hash: ebfbd4b538f948a4
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: '../../../build/usa/build/arm9_ov002.bin'
  hash: '8d1c95acd3e5c0bc'
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: '../../../build/usa/build/arm9_ov003.bin'
  hash: '43c32cd92d96c358'
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: '../../../build/usa/build/arm9_ov004.bin'
  hash: '3dd3721e899588c2'
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: '../../../build/usa/build/arm9_ov005.bin'
  hash: '0b5745a7ea4c8485'
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: '../../../build/usa/build/arm9_ov006.bin'
  hash: '7564a1571fa193b7'
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: '../../../build/usa/build/arm9_ov007.bin'
  hash: '1e8e22600d1d38a6'
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: '../../../build/usa/build/arm9_ov008.bin'
  hash: d908e93b088fddef
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: '../../../build/usa/build/arm9_ov009.bin'
  hash: f471d9b6b69bea56
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: '../../../build/usa/build/arm9_ov010.bin'
  hash: c2097ded5246e6a9
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: '../../../build/usa/build/arm9_ov011.bin'
  hash: '35e9df85a54fa1e1'
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
